name: 08 - Using Variables

on:
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: 'I am a workflow environment variable'
    OVERWRITTEN: 'I will be overwritten in the job'

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'I am a job environment variable'
            OVERWRITTEN: 'I have overwritten the workflow variable'

        steps:
            - name: Print Env Variable
              env:
                STEP_VAR: 'I am a step environment variable'
                step_var2: 'I am another step environment variable'
              run: |
                echo "STEP_VAR: ${{ env.STEP_VAR }}"
                echo "step_var2: $step_var2"
                echo "JOB_VAR: ${{ env.JOB_VAR }}"
                echo "WORKFLOW_VAR: ${{ env.WORKFLOW_VAR }}"
                echo "OVERWRITTEN: ${{ env.OVERWRITTEN }}"
            - name: Overwrite job variable
              env:
                OVERWRITTEN: 'I have been overwritten in the step'
              run: |
                echo "STEP_VAR: ${{ env.OVERWRITTEN }}"
                     