name: 09 - Using Functions

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 20 seconds
              run: |
                echo "Sleeping for 20 seconds..."
                sleep(20)
            - name: Failing Step
              run: |
                echo "This step will fail"
                exit 1
            - name: This step will be skipped
              if: ${{ success() }}
              run: echo "This step runs only if the previous steps were successful."
            - name: I will execute
              if: ${{ failure() }}
              run: echo "This step runs if any of the previous steps failed."
            - name: I will execute always
              if: ${{ cancelled() }}
              run: echo "This step runs regardless of previous step outcomes."